package com.knoweb.salesmanagement.technicalproject.enums;

public enum TechnicalProjectEligibilityReason {
    ELIGIBLE,
    PROJECT_BRIEF_NOT_FOUND,
    CLIENT_VERIFICATION_REQUIRED,
    CLIENT_VERIFICATION_NOT_APPROVED,
    BDM_APPROVAL_REQUIRED,
    BDM_APPROVAL_NOT_APPROVED,
    PROJECT_BRIEF_VERSION_MISMATCH,
    TECHNICAL_PROJECT_ALREADY_EXISTS,
    INVALID_PROJECT_BRIEF_STATUS,
    SALES_OPPORTUNITY_NOT_FOUND
}
