spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    # Safety restrictions for production
    clean-disabled: true

auth:
  cookie:
    secure: true

logging:
  level:
    org.springframework.web: WARN
    com.knoweb.salesmanagement: INFO
